import JSZip from "jszip";
import type { Playbook, Skill, SkillAttachment } from "@/lib/supabase/types";
import { isSafeSkillFile, skillMarkdown } from "@/lib/skill-markdown";
import {
  containsLiteralCredential,
  portableMcpConfig,
  portablePluginManifest,
} from "../../packages/cli/src/plugin-package.js";

const SKILL_NAME = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/** A plugin is an installable snapshot, not a backup of memories or secret values. */
export function buildPlaybookPluginZip(
  playbook: Playbook,
  skills: Skill[],
  attachmentsBySkill: Map<string, SkillAttachment[]>,
  exportedAt = new Date(),
): JSZip {
  const zip = new JSZip();
  const version = `0.${Math.floor(exportedAt.getTime() / 86_400_000)}.${Math.floor((exportedAt.getTime() % 86_400_000) / 1000)}`;
  const manifest = portablePluginManifest({
    name: `${playbook.name}-${playbook.guid.slice(0, 8)}`,
    version,
    description: playbook.description || `Skills and MCP access for the ${playbook.name} playbook.`,
    homepage: `https://agentplaybooks.ai/playbooks/${playbook.guid}`,
    keywords: ["agentplaybooks", "playbook", "agent-skills", "mcp"],
    extensions: {
      "ai.agentplaybooks": {
        playbookGuid: playbook.guid,
        visibility: playbook.visibility,
      },
    },
  });
  if (containsLiteralCredential(JSON.stringify(manifest))) {
    throw new Error("A plugin leírásában lehetséges titok szerepel; előbb javítsd a playbookot.");
  }
  zip.file("plugin.json", `${JSON.stringify(manifest, null, 2)}\n`);

  // The portable MCP configuration never embeds an API key. The host owns
  // authentication; the account server lets a playbook-aware skill select its
  // target by GUID. Generic clients may still need a manual account login.
  zip.file("mcp.json", `${JSON.stringify(portableMcpConfig({
    "agentplaybooks-account": {
      type: "streamable-http",
      url: "https://agentplaybooks.ai/api/mcp/manage",
    },
  }), null, 2)}\n`);

  const added = new Set<string>();
  for (const skill of skills) {
    if (!SKILL_NAME.test(skill.name)) throw new Error(`Érvénytelen skill-név: ${skill.name}`);
    if (added.has(skill.name)) throw new Error(`Ismétlődő skill-név: ${skill.name}`);
    added.add(skill.name);
    const markdown = skillMarkdown(skill);
    if (!markdown) throw new Error(`A(z) ${skill.name} skill leírása hiányzik.`);
    if (containsLiteralCredential(markdown)) throw new Error(`Lehetséges titok a(z) ${skill.name} skillben; az export leállt.`);
    zip.file(`skills/${skill.name}/SKILL.md`, markdown);
    for (const attachment of attachmentsBySkill.get(skill.id) ?? []) {
      if (!isSafeSkillFile(attachment.filename) || typeof attachment.content !== "string") {
        throw new Error(`Nem biztonságos melléklet a(z) ${skill.name} skillben.`);
      }
      if (containsLiteralCredential(attachment.content)) {
        throw new Error(`Lehetséges titok a(z) ${skill.name}/${attachment.filename} mellékletben; az export leállt.`);
      }
      zip.file(`skills/${skill.name}/${attachment.filename}`, attachment.content);
    }
  }

  const playbookInstructions = {
    guid: playbook.guid,
    persona: playbook.persona_system_prompt || null,
    instructions: playbook.instructions || null,
  };
  if (containsLiteralCredential(JSON.stringify(playbookInstructions))) {
    throw new Error("Lehetséges titok a persona vagy az utasítások szövegében; az export leállt.");
  }
  zip.file("ai.agentplaybooks/playbook.json", `${JSON.stringify(playbookInstructions, null, 2)}\n`);
  zip.file("README.md", [
    `# ${playbook.name}`,
    "",
    "Agent Plugins 1.0 package generated by AgentPlaybooks.",
    `Playbook GUID: \`${playbook.guid}\``,
    "",
    "The standard components are `plugin.json`, `skills/`, and `mcp.json`.",
    "The MCP connection targets the AgentPlaybooks account server. Sign in using",
    "your client's own authentication flow, then select this playbook by GUID.",
    "The optional `ai.agentplaybooks/playbook.json` contains persona and project",
    "instructions for AgentPlaybooks-aware importers. Other hosts may ignore it.",
    "No secret values, memories, runs, or canvas documents are included.",
    "For a full private backup, use AgentPlaybooks snapshots instead.",
    "",
  ].join("\n"));
  return zip;
}
