// Generated by scripts/generate-worker-api-routes.mjs. Do not edit.
import type { ApiHandlers, ApiRoute } from "./api-dispatch";
import * as route2 from "../app/api/control/[operation]/route";
import * as route8 from "../app/api/mcp/audit/[guid]/route";
import * as route10 from "../app/api/mcp/config/[serverId]/route";
import * as route11 from "../app/api/mcp/manage/route";
import * as route12 from "../app/api/mcp/[guid]/llms.txt/route";
import * as route13 from "../app/api/mcp/[guid]/tools/[tool]/route";
import * as route14 from "../app/api/mcp/[guid]/route";
import * as route16 from "../app/api/playbooks/[guid]/audit/route";
import * as route17 from "../app/api/playbooks/[guid]/canvas/[slug]/route";
import * as route18 from "../app/api/playbooks/[guid]/canvas/route";
import * as route21 from "../app/api/playbooks/[guid]/memory/[key]/route";
import * as route22 from "../app/api/playbooks/[guid]/memory/route";
import * as route23 from "../app/api/playbooks/[guid]/operations/[operation]/route";
import * as route24 from "../app/api/playbooks/[guid]/runs/[runId]/route";
import * as route25 from "../app/api/playbooks/[guid]/runs/route";
import * as route26 from "../app/api/playbooks/[guid]/secrets/oauth-exchange/route";
import * as route27 from "../app/api/playbooks/[guid]/secrets/proxy/route";
import * as route28 from "../app/api/playbooks/[guid]/secrets/reveal/[name]/route";
import * as route29 from "../app/api/playbooks/[guid]/secrets/[name]/route";
import * as route30 from "../app/api/playbooks/[guid]/secrets/route";
import * as route33 from "../app/api/[[...route]]/route";

export const apiRoutes: ApiRoute[] = [
  { segments: ["collaboration-invites","[token]"], methods: ["GET","POST"], handlers: null },
  { segments: ["connections"], methods: ["GET"], handlers: null },
  { segments: ["control","[operation]"], methods: ["POST"], handlers: route2 as unknown as ApiHandlers },
  { segments: ["manage","backups","[guid]"], methods: ["GET"], handlers: null },
  { segments: ["manage","playbooks","[id]","snapshots","latest"], methods: ["GET"], handlers: null },
  { segments: ["manage","playbooks","[id]","snapshots","[snapshotId]"], methods: ["GET"], handlers: null },
  { segments: ["manage","playbooks","[id]","snapshots"], methods: ["GET","POST"], handlers: null },
  { segments: ["manage","playbooks"], methods: ["GET","POST"], handlers: null },
  { segments: ["mcp","audit","[guid]"], methods: ["GET"], handlers: route8 as unknown as ApiHandlers },
  { segments: ["mcp","config","[serverId]","test"], methods: [], handlers: null },
  { segments: ["mcp","config","[serverId]"], methods: ["GET","POST","PUT","DELETE"], handlers: route10 as unknown as ApiHandlers },
  { segments: ["mcp","manage"], methods: ["GET","POST","OPTIONS"], handlers: route11 as unknown as ApiHandlers },
  { segments: ["mcp","[guid]","llms.txt"], methods: ["GET"], handlers: route12 as unknown as ApiHandlers },
  { segments: ["mcp","[guid]","tools","[tool]"], methods: ["POST"], handlers: route13 as unknown as ApiHandlers },
  { segments: ["mcp","[guid]"], methods: ["GET","POST"], handlers: route14 as unknown as ApiHandlers },
  { segments: ["mcp-registry","search"], methods: ["GET"], handlers: null },
  { segments: ["playbooks","[guid]","audit"], methods: ["GET"], handlers: route16 as unknown as ApiHandlers },
  { segments: ["playbooks","[guid]","canvas","[slug]"], methods: ["GET","PUT","PATCH","DELETE"], handlers: route17 as unknown as ApiHandlers },
  { segments: ["playbooks","[guid]","canvas"], methods: ["GET","POST"], handlers: route18 as unknown as ApiHandlers },
  { segments: ["playbooks","[guid]","collaborators","[collaboratorId]"], methods: ["DELETE"], handlers: null },
  { segments: ["playbooks","[guid]","collaborators"], methods: ["GET","POST"], handlers: null },
  { segments: ["playbooks","[guid]","memory","[key]"], methods: ["PUT","DELETE"], handlers: route21 as unknown as ApiHandlers },
  { segments: ["playbooks","[guid]","memory"], methods: ["GET"], handlers: route22 as unknown as ApiHandlers },
  { segments: ["playbooks","[guid]","operations","[operation]"], methods: ["POST"], handlers: route23 as unknown as ApiHandlers },
  { segments: ["playbooks","[guid]","runs","[runId]"], methods: ["PATCH","DELETE"], handlers: route24 as unknown as ApiHandlers },
  { segments: ["playbooks","[guid]","runs"], methods: ["GET","POST"], handlers: route25 as unknown as ApiHandlers },
  { segments: ["playbooks","[guid]","secrets","oauth-exchange"], methods: ["POST"], handlers: route26 as unknown as ApiHandlers },
  { segments: ["playbooks","[guid]","secrets","proxy"], methods: ["POST","OPTIONS"], handlers: route27 as unknown as ApiHandlers },
  { segments: ["playbooks","[guid]","secrets","reveal","[name]"], methods: ["GET"], handlers: route28 as unknown as ApiHandlers },
  { segments: ["playbooks","[guid]","secrets","[name]"], methods: ["PUT","DELETE"], handlers: route29 as unknown as ApiHandlers },
  { segments: ["playbooks","[guid]","secrets"], methods: ["GET","POST","PUT","DELETE"], handlers: route30 as unknown as ApiHandlers },
  { segments: ["playbooks","[guid]"], methods: ["GET","PUT","DELETE"], handlers: null },
  { segments: ["playbooks"], methods: ["GET","POST"], handlers: null },
  { segments: ["[[...route]]"], methods: ["GET","POST","PUT","DELETE","OPTIONS"], handlers: route33 as unknown as ApiHandlers },
];
