#!/usr/bin/env node

/**
 * Generates a list of known blog slugs from the public/blog directory.
 * This runs at build time to avoid manual maintenance of the slug list.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const blogDir = path.join(__dirname, '..', 'public', 'blog');
const outputFile = path.join(__dirname, '..', 'src', 'lib', 'blog-slugs.generated.ts');

function generateBlogSlugs() {
    if (!fs.existsSync(blogDir)) {
        console.warn('Blog directory not found, creating empty slug list');
        return [];
    }

    const files = fs.readdirSync(blogDir);
    const slugSet = new Set<string>();

    files.forEach((file) => {
        if (!file.endsWith('.md')) return;

        // Extract slug: filename.md or filename.locale.md
        let slug = file.replace(/\.md$/, '');

        // Remove locale suffix if present (e.g., welcome.hu.md -> welcome)
        const parts = slug.split('.');
        if (parts.length > 1 && parts[parts.length - 1].length === 2) {
            parts.pop(); // Remove locale
            slug = parts.join('.');
        }

        slugSet.add(slug);
    });

    return Array.from(slugSet).sort();
}

function writeSlugFile(slugs: string[]) {
    const content = `// Auto-generated file - do not edit manually
// Generated by scripts/generate-blog-slugs.ts

/**
 * List of all known blog post slugs.
 * This file is automatically generated at build time.
 */
export const knownBlogSlugs = ${JSON.stringify(slugs, null, 2)} as const;

export function getKnownBlogSlugs(): string[] {
    return [...knownBlogSlugs];
}
`;

    fs.writeFileSync(outputFile, content, 'utf-8');
}

// Main execution
try {
    console.log('🔍 Scanning blog directory...');
    const slugs = generateBlogSlugs();

    console.log(`📝 Found ${slugs.length} blog post(s):`);
    slugs.forEach(slug => console.log(`   - ${slug}`));

    writeSlugFile(slugs);
    console.log(`✅ Generated: ${path.relative(process.cwd(), outputFile)}`);
} catch (error) {
    console.error('❌ Error generating blog slugs:', error);
    process.exit(1);
}
